/*
* Copyright 2010 Autodesk, Inc.  All rights reserved.
* Use of this software is subject to the terms of the Autodesk license agreement provided at the time of installation or download, 
* or which otherwise accompanies this software in either electronic or hard copy form.
*/

/*! \file 
	\brief Includes all necessary files for integrating \SDKName into your \gameOrSim at runtime. */

#ifndef KyPathdata_GlobalInclude_H
#define KyPathdata_GlobalInclude_H

#include <kypathdata/basesystem/allocatoradapter.h>
#include <kypathdata/basesystem/archive.h>
#include <kypathdata/basesystem/basecomponents.h>
#include <kypathdata/basesystem/basesystem.h>
#include <kypathdata/basesystem/config.h>
#include <kypathdata/basesystem/coordsystem.h>
#include <kypathdata/basesystem/debugdraw.h>
#include <kypathdata/basesystem/estimatedtaskregistry.h>
#include <kypathdata/basesystem/io.h>
#include <kypathdata/basesystem/logger.h>
#include <kypathdata/basesystem/loggerimplementation.h>
#include <kypathdata/basesystem/memorylog.h>
#include <kypathdata/basesystem/memorytree.h>
#include <kypathdata/basesystem/perfcounter.h>
#include <kypathdata/basesystem/perfcountermanager.h>
#include <kypathdata/basesystem/profiler.h>
#include <kypathdata/basesystem/profilermacro.h>
#include <kypathdata/basesystem/taskregistry.h>
#include <kypathdata/basesystem/threadlocalstorage.h>
#include <kypathdata/basesystem/threadlocalstoragecollection.h>
#include <kypathdata/blob/baseblobbuilder.h>
#include <kypathdata/blob/baseblobhandler.h>
#include <kypathdata/blob/blobaggregate.h>
#include <kypathdata/blob/blobarray.h>
#include <kypathdata/blob/blobbuffer.h>
#include <kypathdata/blob/blobfield32.h>
#include <kypathdata/blob/blobfieldarray.h>
#include <kypathdata/blob/blobfieldstring.h>
#include <kypathdata/blob/blobfileheader.h>
#include <kypathdata/blob/blobfilereader.h>
#include <kypathdata/blob/blobfilewriter.h>
#include <kypathdata/blob/blobhandler.h>
#include <kypathdata/blob/blobtyperegistry.h>
#include <kypathdata/blob/endianness.h>
#include <kypathdata/bridge/bridge.h>
#include <kypathdata/bridge/default/defaultcollisionbridge.h>
#include <kypathdata/bridge/default/defaultdrawbridge.h>
#include <kypathdata/bridge/default/defaultfileiobridge.h>
#include <kypathdata/bridge/default/defaultlogbridge.h>
#include <kypathdata/bridge/default/defaultmemorybridge.h>
#include <kypathdata/bridge/default/defaultperfcounterbridge.h>
#include <kypathdata/bridge/default/defaultsocketbridge.h>
#include <kypathdata/bridge/default/deterministictimer.h>
#include <kypathdata/bridge/icollisionbridge.h>
#include <kypathdata/bridge/idatareaderbridge.h>
#include <kypathdata/bridge/idrawbridge.h>
#include <kypathdata/bridge/ifileiobridge.h>
#include <kypathdata/bridge/iperfcounterbridge.h>
#include <kypathdata/bridge/isocketbridge.h>
#include <kypathdata/bridge/ithreadingbridge.h>
#include <kypathdata/bridge/itimerbridge.h>
#include <kypathdata/containers/array.h>
#include <kypathdata/containers/binaryheap.h>
#include <kypathdata/containers/chunkbasedpool.h>
#include <kypathdata/containers/deque.h>
#include <kypathdata/containers/fixedsizebufferpool.h>
#include <kypathdata/containers/fixedsizechunk.h>
#include <kypathdata/containers/kystring.h>
#include <kypathdata/containers/list.h>
#include <kypathdata/containers/multiset.h>
#include <kypathdata/containers/pool.h>
#include <kypathdata/containers/poolhandler.h>
#include <kypathdata/containers/sortedarray.h>
#include <kypathdata/containers/stack.h>
#include <kypathdata/containers/staticdeque.h>
#include <kypathdata/containers/staticstack.h>
#include <kypathdata/containers/stringstream.h>
#include <kypathdata/containers/vector.h>
#include <kypathdata/generic/activeguids.h>
#include <kypathdata/generic/algorithm.h>
#include <kypathdata/generic/basetypes.h>
#include <kypathdata/generic/bitfieldfixedsize.h>
#include <kypathdata/generic/cachesize.h>
#include <kypathdata/generic/callstack.h>
#include <kypathdata/generic/cstdio.h>
#include <kypathdata/generic/datareference.h>
#include <kypathdata/generic/filehandler.h>
#include <kypathdata/generic/guidcompound.h>
#include <kypathdata/generic/guidcompoundblobbuilder.h>
#include <kypathdata/generic/helpers.h>
#include <kypathdata/generic/ilogbridge.h>
#include <kypathdata/generic/imemorybridge.h>
#include <kypathdata/generic/kyguid.h>
#include <kypathdata/generic/macros.h>
#include <kypathdata/generic/memory.h>
#include <kypathdata/generic/pathname.h>
#include <kypathdata/generic/platform.h>
#include <kypathdata/generic/referencemanager.h>
#include <kypathdata/generic/types.h>
#include <kypathdata/generic/typetraits.h>
#include <kypathdata/graph/additionalgraph.h>
#include <kypathdata/graph/additionalgraphblobbuilder.h>
#include <kypathdata/graph/additionalgraphtypes.h>
#include <kypathdata/graph/additionalgraphvisualrepresentation.h>
#include <kypathdata/graph/dynamicadditionalgraph.h>
#include <kypathdata/graph/dynamicadditionalgraphedge.h>
#include <kypathdata/graph/dynamicadditionalgraphvertex.h>
#include <kypathdata/graph/graph.h>
#include <kypathdata/graph/graphcell.h>
#include <kypathdata/graph/graphcellvisualrepresentation.h>
#include <kypathdata/graph/graphedge.h>
#include <kypathdata/graph/graphtypes.h>
#include <kypathdata/graph/graphvertex.h>
#include <kypathdata/graph/graphvisualrepresentation.h>
#include <kypathdata/graph/inputgraphvertex.h>
#include <kypathdata/graph/inputgraphvertexcell.h>
#include <kypathdata/graph/inputgraphvertexcellblobbuilder.h>
#include <kypathdata/graph/inputgraphvertexvisualrepresentation.h>
#include <kypathdata/graph/jumpedgecandidate.h>
#include <kypathdata/graph/jumpedgecandidatearray.h>
#include <kypathdata/graph/jumpedgecandidatesvisualrepresentation.h>
#include <kypathdata/kycrt/math.h>
#include <kypathdata/math/axisalignedbox.h>
#include <kypathdata/math/blob/axisalignedboxdata.h>
#include <kypathdata/math/blob/extrudedpolylinedata.h>
#include <kypathdata/math/blob/extrudedpolylinedatabuilder.h>
#include <kypathdata/math/blob/extrudedrectangledata.h>
#include <kypathdata/math/blob/verticalcylinderdata.h>
#include <kypathdata/math/box2f.h>
#include <kypathdata/math/box2i.h>
#include <kypathdata/math/box3f.h>
#include <kypathdata/math/boxobstacle.h>
#include <kypathdata/math/capsule.h>
#include <kypathdata/math/cardinaldir.h>
#include <kypathdata/math/circle.h>
#include <kypathdata/math/extrudedpolyline.h>
#include <kypathdata/math/extrudedrectangle.h>
#include <kypathdata/math/geometryfunctions.h>
#include <kypathdata/math/horizontalrectangle.h>
#include <kypathdata/math/interval.h>
#include <kypathdata/math/segment.h>
#include <kypathdata/math/triangle3i.h>
#include <kypathdata/math/trigo.h>
#include <kypathdata/math/vec2f.h>
#include <kypathdata/math/vec2i.h>
#include <kypathdata/math/vec3f.h>
#include <kypathdata/math/vec3futils.h>
#include <kypathdata/math/vec3i.h>
#include <kypathdata/math/verticalcylinder.h>
#include <kypathdata/navmesh/bestfirstsearchedgecollisionvisitor.h>
#include <kypathdata/navmesh/bestfirstsearchtraversal.h>
#include <kypathdata/navmesh/breadthfirstsearchedgecollisionvisitor.h>
#include <kypathdata/navmesh/breadthfirstsearchtraversal.h>
#include <kypathdata/navmesh/capsuleintersector.h>
#include <kypathdata/navmesh/closestpoint.h>
#include <kypathdata/navmesh/connectedcomponentnavfloortraversal.h>
#include <kypathdata/navmesh/crossedsectioncapsuleintersector.h>
#include <kypathdata/navmesh/diskcangoquery.h>
#include <kypathdata/navmesh/diskcastquery.h>
#include <kypathdata/navmesh/diskcollisionquery.h>
#include <kypathdata/navmesh/diskexpansionquery.h>
#include <kypathdata/navmesh/diskintersector.h>
#include <kypathdata/navmesh/insideposfromoutsideposquery.h>
#include <kypathdata/navmesh/intersections.h>
#include <kypathdata/navmesh/navcell.h>
#include <kypathdata/navmesh/navcellgrid.h>
#include <kypathdata/navmesh/navcellgridcallbacks.h>
#include <kypathdata/navmesh/navcellptr.h>
#include <kypathdata/navmesh/navcellsafeptr.h>
#include <kypathdata/navmesh/navcellstitcher.h>
#include <kypathdata/navmesh/navcellvisualrepresentation.h>
#include <kypathdata/navmesh/navfloor.h>
#include <kypathdata/navmesh/navfloorptr.h>
#include <kypathdata/navmesh/navfloorsafeptr.h>
#include <kypathdata/navmesh/navfloorsfromboxobstaclequery.h>
#include <kypathdata/navmesh/navhalfedge.h>
#include <kypathdata/navmesh/navhalfedgeptr.h>
#include <kypathdata/navmesh/navhalfedgesafeptr.h>
#include <kypathdata/navmesh/navmesh.h>
#include <kypathdata/navmesh/navmeshcontainercommon.h>
#include <kypathdata/navmesh/navmeshmanager.h>
#include <kypathdata/navmesh/navmeshmanagervisualrepresentation.h>
#include <kypathdata/navmesh/navmeshquerybuffer.h>
#include <kypathdata/navmesh/navmeshqueryserver.h>
#include <kypathdata/navmesh/navmeshsafeptr.h>
#include <kypathdata/navmesh/navmeshstitchdatamanager.h>
#include <kypathdata/navmesh/navmeshtoconnectedcomponents.h>
#include <kypathdata/navmesh/navmeshtraversalcommon.h>
#include <kypathdata/navmesh/navmeshtypes.h>
#include <kypathdata/navmesh/navmeshutils.h>
#include <kypathdata/navmesh/navmeshvisualrepresentation.h>
#include <kypathdata/navmesh/navtriangleptr.h>
#include <kypathdata/navmesh/navtrianglesafeptr.h>
#include <kypathdata/navmesh/navvertexptr.h>
#include <kypathdata/navmesh/navvertexsafeptr.h>
#include <kypathdata/navmesh/nearestobstaclehalfedgefromposquery.h>
#include <kypathdata/navmesh/nearesttrianglefromposquery.h>
#include <kypathdata/navmesh/nmqsarray.h>
#include <kypathdata/navmesh/nmqsbinaryheap.h>
#include <kypathdata/navmesh/nmqsdeque.h>
#include <kypathdata/navmesh/propagationnode.h>
#include <kypathdata/navmesh/propagationquerymemory.h>
#include <kypathdata/navmesh/raycangoquery.h>
#include <kypathdata/navmesh/raycastquery.h>
#include <kypathdata/navmesh/rectangleintersector.h>
#include <kypathdata/navmesh/segmentcangoquery.h>
#include <kypathdata/navmesh/segmentcastquery.h>
#include <kypathdata/navmesh/stitchednavcell.h>
#include <kypathdata/navmesh/stitchednavmesh.h>
#include <kypathdata/navmesh/trianglesfromboxobstaclequery.h>
#include <kypathdata/navmesh/trianglesfromposquery.h>
#include <kypathdata/pathdata/additionaldata.h>
#include <kypathdata/pathdata/pathdata.h>
#include <kypathdata/pathdata/pathdatablobtyperegistry.h>
#include <kypathdata/pathdata/pathdataindex.h>
#include <kypathdata/pathdata/sectordescriptor.h>
#include <kypathdata/pathobject/info/dynamicpathobjectinfo.h>
#include <kypathdata/pathobject/info/pathobjectinfoblobbuilder.h>
#include <kypathdata/pathobject/info/pathobjectinfodata.h>
#include <kypathdata/pathobject/ipathobjectconnexionlink.h>
#include <kypathdata/pathobject/ipathobjectconnexionspace.h>
#include <kypathdata/pathobject/ipathobjectcontrolspace.h>
#include <kypathdata/pathobject/ipathobjectinfo.h>
#include <kypathdata/pathobject/ipathobjecttopology.h>
#include <kypathdata/pathobject/offtheshelf/door/doorpathobjectinfo.h>
#include <kypathdata/pathobject/offtheshelf/door/doorpathobjecttopology.h>
#include <kypathdata/pathobject/offtheshelf/jump/jumppathobjecttopology.h>
#include <kypathdata/pathobject/offtheshelf/ladder/ladderpathobjectconnexionspace.h>
#include <kypathdata/pathobject/offtheshelf/ladder/ladderpathobjectinfo.h>
#include <kypathdata/pathobject/offtheshelf/ladder/ladderpathobjecttopology.h>
#include <kypathdata/pathobject/offtheshelf/teleporter/teleporterpathobjecttopology.h>
#include <kypathdata/pathobject/pathobjectblobbuilder.h>
#include <kypathdata/pathobject/pathobjectdata.h>
#include <kypathdata/pathobject/pathobjectdatatypes.h>
#include <kypathdata/pathobject/topology/connexionlinks/dynamicpathobjectconnexionlink.h>
#include <kypathdata/pathobject/topology/connexionlinks/pathobjectconnexionlinkdata.h>
#include <kypathdata/pathobject/topology/connexionlinks/pathobjectconnexionlinkvisualrepresentation.h>
#include <kypathdata/pathobject/topology/connexionspaces/dynamicpathobjectconnexionspace_cylinder.h>
#include <kypathdata/pathobject/topology/connexionspaces/dynamicpathobjectconnexionspace_extrudedpolyline.h>
#include <kypathdata/pathobject/topology/connexionspaces/dynamicpathobjectconnexionspace_extrudedrectangle.h>
#include <kypathdata/pathobject/topology/connexionspaces/pathobjectconnexionspacedata.h>
#include <kypathdata/pathobject/topology/connexionspaces/pathobjectconnexionspacedata_cylinder.h>
#include <kypathdata/pathobject/topology/connexionspaces/pathobjectconnexionspacedata_extrudedpolyline.h>
#include <kypathdata/pathobject/topology/connexionspaces/pathobjectconnexionspacedata_extrudedrectangle.h>
#include <kypathdata/pathobject/topology/connexionspaces/pathobjectconnexionspacevisualrepresentation.h>
#include <kypathdata/pathobject/topology/connexionspaces/pathobjectconnexionspacevisualrepresentation_cylinder.h>
#include <kypathdata/pathobject/topology/controlspaces/dynamicpathobjectcontrolspace.h>
#include <kypathdata/pathobject/topology/controlspaces/dynamicpathobjectcontrolspace_box.h>
#include <kypathdata/pathobject/topology/controlspaces/dynamicpathobjectcontrolspace_extrudedpolyline.h>
#include <kypathdata/pathobject/topology/controlspaces/dynamicpathobjectcontrolspace_extrudedrectangle.h>
#include <kypathdata/pathobject/topology/controlspaces/pathobjectcontrolspacedata.h>
#include <kypathdata/pathobject/topology/controlspaces/pathobjectcontrolspacedata_box.h>
#include <kypathdata/pathobject/topology/controlspaces/pathobjectcontrolspacedata_extrudedpolyline.h>
#include <kypathdata/pathobject/topology/controlspaces/pathobjectcontrolspacedata_extrudedrectangle.h>
#include <kypathdata/pathobject/topology/controlspaces/pathobjectcontrolspacevisualrepresentation.h>
#include <kypathdata/pathobject/topology/controlspaces/pathobjectcontrolspacevisualrepresentation_box.h>
#include <kypathdata/pathobject/topology/dynamicpathobjecttopology.h>
#include <kypathdata/pathobject/topology/pathobjecttopologyblobbuilder.h>
#include <kypathdata/pathobject/topology/pathobjecttopologydata.h>
#include <kypathdata/pathobject/topology/pathobjecttopologyvisualrepresentation.h>
#include <kypathdata/seedgraph/seedgraphdatatypes.h>
#include <kypathdata/seedgraph/seedgraphedgedata.h>
#include <kypathdata/seedgraph/seedgraphvertexdata.h>
#include <kypathdata/shapes/axisalignedboxvolume.h>
#include <kypathdata/shapes/draw.h>
#include <kypathdata/shapes/extrudedpolylinevolume.h>
#include <kypathdata/shapes/extrudedrectanglevolume.h>
#include <kypathdata/shapes/ivolume.h>
#include <kypathdata/shapes/verticalcylindervolume.h>
#include <kypathdata/stats/graphstat.h>
#include <kypathdata/visualsystem/axisframe.h>
#include <kypathdata/visualsystem/axisframevisualrepresentation.h>
#include <kypathdata/visualsystem/colorpalette.h>
#include <kypathdata/visualsystem/grid.h>
#include <kypathdata/visualsystem/gridvisualrepresentation.h>
#include <kypathdata/visualsystem/ivisualgeometry.h>
#include <kypathdata/visualsystem/ivisualpicker.h>
#include <kypathdata/visualsystem/ivisualrenderer.h>
#include <kypathdata/visualsystem/visualboxvertices.h>
#include <kypathdata/visualsystem/visualcolor.h>
#include <kypathdata/visualsystem/visualdescription.h>
#include <kypathdata/visualsystem/visualgeometrybuilder.h>
#include <kypathdata/visualsystem/visualrepresentation.h>

#endif //KyPathdata_GlobalInclude_H
